name: Arch Linux

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  arch:
    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          sudo pacman -Syu --noconfirm wget git openmp base-devel bc zip
          wget https://raw.githubusercontent.com/username/repo/branch/build.sh
          bash build.sh